### ISSUE TITLE
Placeholder seems to extend to other elements

### ISSUE THREAD

**Issue by maicol07** [fornewid/placeholder#6] opened 2023-08-31 12:11 UTC
## Describe the bug
It seems that placeholder also applies to other elements (I don't know why), where it isn't applied.

## To Reproduce
I don't know exactly how to reproduce it, but the project in the recording below is this one: https://github.com/maicol07/GameLibrary

## Expected behavior
Placeholder is only applied to elements where the modifier is applied

## Screenshots
Example (see the home navbar item and the FAB when seeing a game):
https://github.com/fornewid/placeholder/assets/9463142/fda2efe2-4f6a-4216-96fd-9be6ff38124b

## Environment
 - Android OS version: Android 13
 - Device: Zenfone 8 Flip
 - material-motion-compose version: Not used

**Comment by fornewid** [comment] 2023-08-31 17:31
`placeholder()` uses `DrawModifier` simply.
This means that it only applies to a composable that uses Modifier with `placeholder()` applied.
So I think, this is not possible in the current implementation. 🤔 

Just remove `placeholder()` and see if the problem reproduces.
If not, please share executable and reproducible code snippet.
(I couldn't execute your project.)

**Comment by adhirajsinghchauhan** [comment] 2023-09-01 05:23
I can reproduce. Applying `shimmer` placeholder to one element also bleeds that effect through to icons (only icons!) throughout the app, but not all of them.

For the time being I've switched to `fade` because it doesn't happen with that. Can't post a code sample yet, we're working in an internal branch.

**Comment by fornewid** [comment] 2023-09-07 14:17
@adhirajsinghchauhan 
Oh, thank you for detail description!

Recently I've been focusing on preparing a presentation.
So, sorry for the late. 🙇 

I'll check this out soon.

**Comment by adhirajsinghchauhan** [comment] 2023-09-07 15:42
No problems, take your time. https://issuetracker.google.com/issues/297231233 might be related, though I don't see how.
> icons randomly disappear after scrolling (scrolling them off screen and back sometimes makes the icon come back, but others disappear)

**Comment by ColtonIdle** [comment] 2023-09-11 01:39
I'm having this problem too! But I'm not yet using this library. lol. I'm using accompanist and getting this issue so i want to move to this library. looks like it might just be a compose issue.

**Comment by fornewid** [comment] 2023-09-11 02:03
> looks like it might just be a compose issue.

@ColtonIdle 
Yes. I think so too. The issue is caused by Compose 1.6

**Comment by ColtonIdle** [comment] 2023-09-14 04:52
The problem goes away with compose 1.6-alpha05! Hooray. Looks like it was caused by alpha04 and below!

**Comment by adhirajsinghchauhan** [comment] 2023-10-23 02:11
^ Can confirm; should be closed as it's not relevant anymore. It hasn't popped up again in any of the newer Compose alpha versions thankfully (latest is 08 right now).

**Closed as completed** 2023-11-17 13:08 UTC
